USE [MovimentosManuais]
GO

/****** Object:  Tabela [dbo].[PRODUTO]  ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUTO](
	[COD_PRODUTO] [CHAR](4) NOT NULL,
	[DES_PRODUTO] [VARCHAR](30) NULL,
	[STA_STATUS] [CHAR](1) NULL,
CONSTRAINT [PK_PRODUTO] PRIMARY KEY CLUSTERED 
(
  [COD_PRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRODUTO] ADD CONSTRAINT [CHK_PRODUTO_STA_STATUS] CHECK ([STA_STATUS] IN ('A', 'I'))

/****** Object:  Tabela [dbo].[PRODUTO_COSIF]  ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUTO_COSIF](
    [COD_COSIF] [CHAR](11) NOT NULL,
	[COD_PRODUTO] [CHAR](4) NOT NULL,
	[COD_CLASSIFICACAO] [CHAR](6) NULL,
	[STA_STATUS] [CHAR](1) NULL,
CONSTRAINT [PK_PRODUTO_COSIF] PRIMARY KEY CLUSTERED 
(
	[COD_COSIF] ASC, [COD_PRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRODUTO_COSIF]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTO_COSIF_PRODUTO_COD_PRODUTO] FOREIGN KEY([COD_PRODUTO])
REFERENCES [dbo].[PRODUTO] ([COD_PRODUTO])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PRODUTO_COSIF] CHECK CONSTRAINT [FK_PRODUTO_COSIF_PRODUTO_COD_PRODUTO]
GO

ALTER TABLE [dbo].[PRODUTO_COSIF] ADD CONSTRAINT [CHK_PRODUTO_COSIF_STA_STATUS] CHECK ([STA_STATUS] IN ('A', 'I'));
GO

/****** Object:  Tabela [dbo].[MOVIMENTO_MANUAL]  ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MOVIMENTO_MANUAL](
    [DAT_MES] [INT] NOT NULL,
    [DAT_ANO] [INT] NOT NULL,
    [NUM_LANCAMENTO] [INT] NOT NULL,
	[COD_PRODUTO] [CHAR](4) NOT NULL,
    [COD_COSIF] [CHAR](11) NOT NULL,
    [VAL_VALOR] DECIMAL(18, 2) NOT NULL,
    [DES_DESCRICAO] VARCHAR(50) NOT NULL,
    [DAT_MOVIMENTO] SMALLDATETIME NOT NULL,
    [COD_USUARIO] VARCHAR(15) NOT NULL,
CONSTRAINT [PK_MOVIMENTO_MANUAL] PRIMARY KEY CLUSTERED 
(
	[DAT_MES] ASC, [DAT_ANO] ASC, [NUM_LANCAMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MOVIMENTO_MANUAL]  WITH CHECK ADD  CONSTRAINT [FK_MOVIMENTO_MANUAL_PRODUTO_COSIF_COD_COSIF_COD_PRODUTO] 
FOREIGN KEY([COD_COSIF], [COD_PRODUTO])
REFERENCES [dbo].[PRODUTO_COSIF] ([COD_COSIF], [COD_PRODUTO])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[MOVIMENTO_MANUAL] CHECK CONSTRAINT [FK_MOVIMENTO_MANUAL_PRODUTO_COSIF_COD_COSIF_COD_PRODUTO]
GO

/****** Object:  Procedimento [SP_CONSULTA_MOVIMENTO_MANUAL]  ******/
CREATE PROCEDURE [dbo].[SP_CONSULTA_MOVIMENTO_MANUAL]
AS
BEGIN
    SELECT
        MM.DAT_MES,
        MM.DAT_ANO	,
        MM.COD_PRODUTO,
        P.DES_PRODUTO,
        MM.NUM_LANCAMENTO,
        MM.DES_DESCRICAO,
        MM.VAL_VALOR
    FROM MOVIMENTO_MANUAL MM
    INNER JOIN PRODUTO P ON MM.COD_PRODUTO = P.COD_PRODUTO
    ORDER BY MM.DAT_ANO, MM.DAT_MES, MM.NUM_LANCAMENTO
END
GO

/****** Carga na tabela [PRODUTO] ******/
INSERT INTO [dbo].[PRODUTO]
           ([COD_PRODUTO]
           ,[DES_PRODUTO]
           ,[STA_STATUS])
     VALUES
           ('0001','Produto 1','A'),
		   ('0002','Produto 2','A'),
		   ('0003','Produto 3','I')
GO

/****** Carga na tabela [PRODUTO_COSIF] ******/
INSERT INTO [dbo].[PRODUTO_COSIF]
           ([COD_COSIF]
           ,[COD_PRODUTO]
           ,[COD_CLASSIFICACAO]
           ,[STA_STATUS])
     VALUES
           ('00000000001','0001','NORMAL','A'),
		   ('00000000002','0001','NORMAL','A'),
		   ('00000000003','0001','NORMAL','A'),
		   ('00000000004','0002','NORMAL','A'),
		   ('00000000005','0002','NORMAL','A')
GO

/****** Carga na tabela [MOVIMENTO_MANUAL] ******/
INSERT INTO [dbo].[MOVIMENTO_MANUAL]
           ([DAT_MES]
           ,[DAT_ANO]
           ,[NUM_LANCAMENTO]
           ,[COD_PRODUTO]
           ,[COD_COSIF]
           ,[VAL_VALOR]
           ,[DES_DESCRICAO]
           ,[DAT_MOVIMENTO]
           ,[COD_USUARIO])
     VALUES
           (01,2024,01,'0001','00000000001',20.0, 'Movimento Manual 1',GETDATE(),'ADMIN'),
		   (02,2024,01,'0001','00000000002',22.0, 'Movimento Manual 2',GETDATE(),'ADMIN')
GO
